services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23230906
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bakery-network

  bakery:
    build:
      context: ./bakery
      dockerfile: Dockerfile
    container_name: bakery
    ports:
      - "8082:8082"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/bakery
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 23230906
        SPRING_JPA_HIBERNATE_DDL-AUTO: validate
    depends_on:
      - postgres
    networks:
      - bakery-network

  cart:
    build:
      context: ./CartBakery
      dockerfile: Dockerfile
    container_name: cart
    ports:
      - "8083:8083"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/cartBakery
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 23230906
        SPRING_JPA_HIBERNATE_DDL-AUTO: validate
    depends_on:
      - postgres
    networks:
      - bakery-network

  order:
    build:
      context: ./OrderBakery
      dockerfile: Dockerfile
    container_name: order
    ports:
      - "8084:8084"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/orderBakery
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 23230906
        SPRING_JPA_HIBERNATE_DDL-AUTO: validate
    depends_on:
      - postgres
    networks:
      - bakery-network

  admin:
    build:
      context: ./AdminBakery
      dockerfile: Dockerfile
    container_name: admin
    ports:
      - "8086:8086"
    environment:
      CATALOG_SERVICE_URL: http://bakery:8082/api
      ORDER_SERVICE_URL: http://order:8084/api
    depends_on:
      - bakery
      - order
    networks:
      - bakery-network

  frontend:
    build:
      context: ./bakery-project
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - bakery
      - cart
      - order
      - admin
    networks:
      - bakery-network

volumes:
  postgres_data:

networks:
  bakery-network:
    driver: bridge  
    attachable: true
    internal: false