spring.application.name=bakery
spring.datasource.url=jdbc:postgresql://postgres:5432/bakery
spring.datasource.username=postgres
spring.datasource.password=23230906
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
server.port=8082


spring.web.cors.allowed-origins=http://frontend
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.root-dir=/app/uploads
app.upload.products-dir=/app/uploads/products

spring.security.user.name=
spring.security.user.password=

