spring.application.name=bakery
spring.datasource.url=jdbc:postgresql://postgres:5432/bakery
spring.datasource.username= postgres
spring.datasource.password= 23230906
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
server.port=8082


spring.web.cors.allowed-origins=http://frontend
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*

spring.security.user.name=
spring.security.user.password=

